name: go_echo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit_tests:
    name: build and unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  aks:
    name: run on aks
    concurrency: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gambtho/aks_create_action@main
        with:
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
          STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          STORAGE_CONTAINER_NAME: ${{ secrets.STORAGE_CONTAINER_NAME }}
          STORAGE_ACCESS_KEY: ${{ secrets.STORAGE_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          CREATE_ACR: true
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CLUSTER_NAME }}.azurecr.io
          username: ${{ secrets.ARM_CLIENT_ID }}
          password: ${{ secrets.ARM_CLIENT_SECRET }}
      - run: >
          docker build . -t ${{ secrets.CLUSTER_NAME }}.azurecr.io/${{
          secrets.APP_NAME }}:${{ github.sha }}

          docker push ${{ secrets.CLUSTER_NAME }}.azurecr.io/${{ secrets.APP_NAME }}:${{ github.sha }}
        name: Docker push
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          resource-group: ${{ secrets.RESOURCE_GROUP_NAME }}
      - run: >
          kubectl create namespace ${{ secrets.NAMESPACE }} --dry-run -o json |
          kubectl apply -f -
      - uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.CLUSTER_NAME }}.azurecr.io
          container-registry-username: ${{ secrets.ARM_CLIENT_ID }}
          container-registry-password: ${{ secrets.ARM_CLIENT_SECRET }}
          secret-name: ${{ secrets.SECRET_NAME }}
          namespace: ${{ secrets.NAMESPACE }}
          force: true
      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/deployment.yaml
            manifests/service.yaml
            manifests/ingress.yaml
          images: >
            ${{ secrets.CLUSTER_NAME }}.azurecr.io/${{ secrets.APP_NAME }}:${{
            github.sha }}
          imagepullsecrets: |
            ${{ secrets.SECRET_NAME }}
          namespace: ${{ secrets.NAMESPACE }}
      - uses: imiller31/install-osm-action@main
